kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: skanmotreferansenr
  namespace: {{ NAMESPACE }}
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: SKANMOTREFERANSENR_GETMETADATAFOERSTESIDEURL
      value: {{ SKANMOTREFERANSENR_GETMETADATAFOERSTESIDEURL }}
    - name: SKANMOTREFERANSENR_DOKARKIVJOURNALPOSTURL
      value: {{ SKANMOTREFERANSENR_DOKARKIVJOURNALPOSTURL }}
    - name: SKANMOTREFERANSENR_STSURL
      value: {{ SKANMOTREFERANSENR_STSURL }}
    - name: SKANMOTREFERANSENR_SFTP_PRIVATEKEY
      value: /var/run/secrets/nais.io/keys/privatekey
    - name: SKANMOTREFERANSENR_SFTP_HOSTKEY
      value: /var/run/secrets/nais.io/keys/hostkey
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
       - {{this }}
      {{/each}}
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /prometheus
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      memory: 1024Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVSKANMOTREFERANSE }}
        mountPath: /var/run/secrets/nais.io/srvskanmotreferanse
      - kvPath: {{ SKANMOTREFERANSENR_VAULT }}
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: {{ SFTP_KEYS }}
        mountPath: /var/run/secrets/nais.io/keys